# APIs
openai_api_key: "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"
openai_api_base: "https://api.openai.com/v1/chat/completions" # or your own proxy
google_api_key: "AIzaSyBXHrAngrjce0eBaDMrehZc-IiY8JI6ThQ"
tavily_api_key: "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"

# Ollama Config
run_local: "No" # must have ollama runnig in ur PC if Yes
local_llm: "openhermes" # mistral, llama2 ...

# Model Config
models: "openai"

# Document Config
doc_url: 
  - "https://nagi.fun/llm-5-transformer"  
  - "https://nagi.fun/llm-4-wavenet"  
